### ISSUE TITLE
Feature Request and Thank You!

### ISSUE THREAD

**Issue by HerrNiklasRaab** [jonsamwell/flutter_simple_dependency_injection#6]
Hello, 

thank you for your work you have done already!

Two questions: 
- Are you planning to maintain this package in the future, because we want to implement it into our software.
- Is it planned to have property injection with annotations like @injectable? This would be great.

Thanks for your time,

Niklas

**Comment by husky-machines** [comment]
Hi @HerrNiklasRaab 

Yes I am actively maintaining this and using it in a couple of app in production (ios and android).

The @Injectable is a tricky one as this is a runtime dependency injector rather than a compile time one.

I favour the approach of simple code rather than relying on build time code generation.

In that essence I modularize the dependency injection creating a container that invokes smaller module containers to manage the dependencies of that part of the app.

**Comment by jonsamwell** [comment]
Hi @HerrNiklasRaab

Yes I am actively maintaining this and using it in a couple of apps in production (ios and android).

The @Injectable is a tricky one as this is a runtime dependency injector rather than a compile time one. Keep in mind that we cannot use mirrors (reflection) in flutter as it is not included so the annotation route is a compile time one.

I favour the approach of simple code rather than relying on build time code generation.

In that essence I modularize the dependency injection creating a container that invokes smaller module containers to manage the dependencies of that part of the app.  This helps manage a large number of dependencies.

**Comment by HerrNiklasRaab** [comment]
Ok, great the we will also use this in production. With @Injectible I thought so because i saw this package: https://github.com/ltackmann/dice. But your Api is "more friendly", this is why i chose yours.

Just tried to use your package, works like charme :)

**Comment by jonsamwell** [comment]
Awesome, thanks for using it. Let me know if you need a new feature or
anything.

Jon

**Comment by HerrNiklasRaab** [comment]
Did you checked out the dice project how they handle the @Injectable?

**Comment by jonsamwell** [comment]
Hi @HerrNiklasRaab dice uses mirrors (reflection) to handle the @Injectable annotation so I won't be able to use this in Flutter as it does not come with mirrors.

**Comment by HerrNiklasRaab** [comment]
Ok, no problem, still great software!

**Comment by jonsamwell** [comment]
Thanks!
